title: Web CV
description: SITE 1101 personal web CV
author: Shahsanam
baseurl: /cv
url: https://shahsanam777.github.io
github_username: shahsanam777
github_repo_url: https://github.com/shahsanam777/cv
codecademy_url: https://www.codecademy.com/profiles/blog5811781362

markdown: kramdown
